apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actividad4-ingress
spec:
  rules:
  - host: actividad4.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: actividad4-service
            port:
              number: 3000
